#!/bin/bash

################################################################################
# Simple script to install ROS Kinetic on Raspbian Stretch OS
# 	- https://www.raspberrypi.org/downloads/raspbian/
#	- http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi
#
# Example:
# install_ros_kinetic
################################################################################

sudo apt-get install -y dirmngr

sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get install -y python-rosdep python-rosinstall-generator python-wstool python-rosinstall build-essential cmake

sudo rosdep init
rosdep update

mkdir -p ~/ros_catkin_ws
cd ~/ros_catkin_ws

# ROS-Comm
rosinstall_generator ros_comm --rosdistro kinetic --deps --wet-only --tar > kinetic-ros_comm-wet.rosinstall
wstool init src kinetic-ros_comm-wet.rosinstall

# Desktop
# rosinstall_generator desktop --rosdistro kinetic --deps --wet-only --tar > kinetic-desktop-wet.rosinstall
# wstool init src kinetic-desktop-wet.rosinstall

# Robot
# rosinstall_generator robot --rosdistro kinetic --deps --wet-only --tar > kinetic-robot-wet.rosinstall
# wstool init src kinetic-robot-wet.rosinstall

cd ~/ros_catkin_ws
rosdep install -y --from-paths src --ignore-src --rosdistro kinetic -r --os=debian:stretch
